analytics: {}
color:
  brandColors:
    - '#050505'
    - '#EA10D6'
    - '#69F50E'
    - '#10D60F'
    - '#1179FE'
  brandStrength: 0.493303
  lightness: 1
  rhythmicContrast: 0
  saturation: 0.734375
cta: {}
layout_spectrum: 0
name: friday
opengraph: {}
purpose: []
typography_spectrum: 0.19866
