analytics: {}
color:
  brandColors:
    - '#000000'
    - '#DEDEDE'
    - '#C76FAC'
    - '#14CC0C'
    - '#C71078'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 0.243303
  saturation: 1
cta: {}
layout_spectrum: 0.891183
name: friday
opengraph: {}
purpose: []
typography_spectrum: 0.048549
