analytics: {}
color:
  brandColors:
    - '#000000'
    - '#DEDEDE'
    - '#C76FAC'
    - '#14CC0C'
    - '#C71078'
  brandStrength: 0.834821
  lightness: 1
  rhythmicContrast: 1
  saturation: 0.956473
cta: {}
layout_spectrum: 0.891183
name: friday
opengraph: {}
purpose: []
typography_spectrum: 0.048549
