analytics: {}
color:
  brandColors:
    - '#050505'
    - '#EA10D6'
    - '#69F50E'
    - '#10D60F'
    - '#1179FE'
  brandStrength: 0.685825
  lightness: 0
  rhythmicContrast: 0
  saturation: 0.87779
cta: {}
layout_spectrum: 0.891183
name: friday
opengraph: {}
purpose: []
typography_spectrum: 0.19866
